//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace İşTakipProjesi.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblGörevDetaylar
    {
        public int ID { get; set; }
        public Nullable<int> Görev { get; set; }
        public string GörevAçıklama { get; set; }
        public string Saat { get; set; }
        public string Tarihi { get; set; }
    
        public virtual TblGörevler TblGörevler { get; set; }
    }
}
